### PR TITLE
Intercom sessions fix [Again]

### LINKED ISSUE #113: Intercom app does not sign in user when authenticated

### PR DESCRIPTION
**Pull request by pranav7**
Fixes: https://github.com/pranav7/cadet-app/issues/113

### CODE REVIEW

File: app/controllers/intercom_controller.rb [hunk 1]
```diff
@@ -7,12 +7,21 @@ class IntercomController < ApplicationController # rubocop:disable Metrics/Class
 
   def sheets
     intercom_data = validate_request_and_decrtypt_data
+    log("Processing sheets request intercom_data=#{intercom_data.inspect}")
```
Comment (pranav7) [inline app/controllers/intercom_controller.rb]:
```suggestion
    log("Processing sheets request")
```

File: app/controllers/intercom_controller.rb [hunk 2]
```diff
@@ -7,12 +7,21 @@ class IntercomController < ApplicationController # rubocop:disable Metrics/Class
...
+
     company = CompanySetting.find_by_intercom_workspace_id!(intercom_data.app_id).company
     board = company.boards.friendly.find(company.company_setting.intercom_default_board_slug)
-    user = User.find_by_email(intercom_data.email)
+    log("Company=#{company.subdomain} board=#{board.slug}")
 
-    sign_in(user) if user
+    user = User.find_by_email(intercom_data.email)
+    if user
+      log("User found, #{user.inspect}")
```
Comment (pranav7) [inline app/controllers/intercom_controller.rb]:
```suggestion
      log("User found, #{user.id}")
```
